# Generated by Django 2.1.2 on 2018-10-05 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='タイトル')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
                ('shooting_time', models.DateTimeField(blank=True, null=True, verbose_name='撮影時間')),
                ('geo_location', models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='緯度：-90.000000 ~ 90.000000 / 経度: -180.000000 ~ 180.000000（小数点以下６桁以内）を指定します。緯度と統計はカンマ「,」で区切ります。例：35.658581,139.745433', regex='-?([0-8]?[0-9]|90)\\.[0-9]{1,6},\\s?-?((1?[0-7]?|[0-9]?)[0-9]|180)\\.[0-9]{1,6}$')], verbose_name='経度緯度')),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='撮影場所')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '画像データ',
                'verbose_name_plural': '画像データ',
            },
        ),
    ]
